version: '3.8'

services:
  valkey:
    image: valkey/valkey
    container_name: valkey-server
    ports:
      - "6379:6379"
    volumes:
      - valkey-data:/data

volumes:
  valkey-data: